### ISSUE TITLE
Determine how to rebuild dependent images for ci runs 

### ISSUE THREAD

**Issue by jchauncey** [deis/docker-base#3]
Would be nice when a pr is submitted to this job it rebuilt all dependent images for an e2e run

**Comment by krancour** [comment]
I'm somewhat against this. I think it _sounds_ like it would save us a lot of work, but I also think it makes a huge assumption that updating the `FROM` directive on all the derivative images is all that needs to be done. That's not necessarily always the case. If things are added or removed from the base image (or the distro changes) the effect on derivative images may not always be so trivial.

**Comment by bacongobbler** [comment]
I second what @krancour says. When a new release is tagged, updating just the FROM clause in downstream apps is not always going to the case, such as with library deprecations or major distro upgrades as mentioned previously.

However, having some form to notify downstream maintainers that there's a new docker-base update... That would be a great enhancement without too much impact on a downstream maintainers' workflow.
